export const modules = [
  { slug: "cotizaciones", name: "Cotizaciones", area: "Comercial", phase: 3,
    description: "Presupuesta cada servicio con sus tramos, carga y costos.",
    scope: ["Carga general y refrigerada; tarifas por viaje, tonelada, volumen o unidad.", "Distancias, peajes, viáticos y gastos por tramo.", "Versiones, monedas y aprobación de la cotización."] },
  { slug: "viajes", name: "Viajes y operaciones", area: "Operaciones", phase: 4,
    description: "Conecta la orden de servicio con el recorrido y la entrega.",
    scope: ["Asignación de vehículo, remolque y conductores.", "Tramos, cruces de frontera y evidencias de entrega.", "Gastos reales y comparación con lo presupuestado."] },
  { slug: "flota", name: "Flota y llantas", area: "Operaciones", phase: 6,
    description: "Conoce el historial y la condición de cada unidad.",
    scope: ["Ficha de vehículos desde la fase 2.", "Diagrama por ejes y posiciones de llantas; inspecciones y rotaciones.", "Desgaste medido, daños y estimaciones presentados por separado."] },
  { slug: "taller", name: "Taller y mantenimiento", area: "Soporte", phase: 6,
    description: "Planifica intervenciones y registra recursos por vehículo.",
    scope: ["Órdenes de trabajo, mano de obra y repuestos.", "Programación por kilómetros, horas o fecha.", "Mantenimiento de equipos de refrigeración y accesorios."] },
  { slug: "almacen", name: "Compras y almacén", area: "Soporte", phase: 5,
    description: "Controla insumos y repuestos desde la compra hasta su consumo.",
    scope: ["Proveedores, compras y recepciones.", "Kardex, transferencias, reservas y devoluciones.", "Consumo de repuestos asociado a órdenes de trabajo."] },
  { slug: "personas", name: "Personas y empresas", area: "Organización", phase: 2,
    description: "Centraliza clientes, proveedores y el equipo de trabajo.",
    scope: ["Clientes y proveedores con documentos de distintos países.", "Conductores, licencias y vencimientos desde la fase 2.", "RR. HH., contratos, asistencia y permisos en la fase 7."] },
  { slug: "finanzas", name: "Finanzas y SUNAT", area: "Administración", phase: 8,
    description: "Relaciona costos, cobros y comprobantes con cada servicio.",
    scope: ["Caja, cuentas por cobrar y pagar; liquidaciones.", "Facturación de servicios, notas y seguimiento de respuestas SUNAT.", "Separación de pruebas y producción; historial de emisiones."] },
  { slug: "seguimiento", name: "GPS y seguimiento", area: "Operaciones", phase: 9,
    description: "Ubicación, historial y llegada estimada de las unidades.",
    scope: ["Dispositivos compatibles y seguimiento autorizado del conductor.", "Posición con fecha de actualización y estado de señal.", "ETA estimada según ruta, paradas y demoras conocidas."] },
  { slug: "configuracion", name: "Configuración", area: "Administración", phase: 1,
    description: "Un espacio propio para personalizar la empresa y su operación.",
    scope: ["Razón social, sucursales, logos, colores y plantillas.", "Usuarios, permisos, países, monedas y zonas horarias.", "Configuración de SUNAT e integraciones en sus respectivas fases."] },
] as const;

export const phases = [
  { number: 0, name: "Base técnica", result: "Next.js, API modular, validaciones y preparación de la HP." },
  { number: 1, name: "Empresa y acceso", result: "MySQL, usuarios, permisos, auditoría y personalización." },
  { number: 2, name: "Datos maestros", result: "Clientes, proveedores, conductores, vehículos y catálogos." },
  { number: 3, name: "Cotizaciones", result: "Carga, tramos, costos, monedas y versiones aprobadas." },
  { number: 4, name: "Operaciones", result: "Órdenes, viajes, asignaciones, gastos reales y entregas." },
  { number: 5, name: "Compras y almacén", result: "Recepciones, existencias, movimientos y consumo de repuestos." },
  { number: 6, name: "Taller y flota", result: "Mantenimiento, diagrama de llantas e historial de condición." },
  { number: 7, name: "Recursos humanos", result: "Legajos, contratos, asistencia, permisos y vencimientos." },
  { number: 8, name: "Finanzas y SUNAT", result: "Liquidaciones, cobranza y emisión electrónica validada." },
  { number: 9, name: "GPS y cadena de frío", result: "Telemetría, mapas, ETA y sensores compatibles." },
  { number: 10, name: "Escala y puesta en marcha", result: "Pruebas de carga, restauración, reportes y piloto operativo." },
] as const;
